### ISSUE TITLE
Master measure color: different behavior between native and extension with single color

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#130]
1: Create a scatterplot and have the first measure a measure with a set measure color in master measure.
2: Choose single color
Notice in the PP that there is a property library color. 
3: Choose measure 
Nothing happens and the measure color is not applied

If the same thing is done in the native object then the property is not seen

**Comment by quanho** [comment]
In web/assets/client/utils/color-support.js in sense-client there is a check against data.visualization to see if this properties should be supported or not. The current list of visualizations which do not support this properties is 'scatterplot' and 'map'.

So this will be fixed automatically when we have a new scatter plot as a native scatter plot.
