### ISSUE TITLE
Missing asterisk * next to title when disclaimer shows (compressed data view)

### ISSUE THREAD

**Issue by evahri** [qlik-oss/sn-scatter-plot#161]
In old scatter plot, an asterisk * is shown next to the title. This is not the case in new scatter plot.
![image](https://user-images.githubusercontent.com/92570566/149796183-9232710a-8435-479b-8c27-f94b56d9da1b.png)

**Comment by jjxie** [comment]
It's an issue for all nebula charts. There is an improvement for it VIZ-234.
