### ISSUE TITLE
Cannot drag inside a scatter plot, it activates lasso selection instead

### ISSUE THREAD

**Issue by evahri** [qlik-oss/sn-scatter-plot#166]
Dragging in the chart doesn't bring you around to the desired part of the chart, instead you're in the lasso selection mode.
It is the same behavior when you're in VE menu too.

See movie:
![scatterplot_drag_turns_to_select_mode](https://user-images.githubusercontent.com/92570566/149940882-3bdfd4eb-8e49-4e4f-96eb-d960774cce37.gif)

**Comment by quanho** [comment]
Cannot reproduce this with the latest.
