### ISSUE TITLE
Mobile: Disclaimer text not aligned to left making it easily truncated

### ISSUE THREAD

**Issue by evahri** [qlik-oss/sn-scatter-plot#194]
1. Open a scatter plot with compressed data on mobile
2. In standing/portrait mode, the disclaimer text *Providing an overivew of... isn't aligned to the left so it gets truncated very easily.
![image](https://user-images.githubusercontent.com/92570566/150758628-d390632e-b94d-4806-89eb-cd8d3994d114.png)

**Comment by quanho** [comment]
This disclaimer is consistent to other la-vie charts!
