### ISSUE TITLE
Custom tooltip gets invalid parameters in compressed mode

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#203]
1: Create a scatter plot with compressed data
2: Add some of the things you can add to custom tooltip; image, measure, chart
3: Hoover on the compressed data - invalid parameters error pops up

After some discussions with @tasseKATT it is probably better to just show the normal tooltip in compressed mode and not custom tooltip. So in compressed data only "Density: XXX" shouls show and nothing from custom tooltip. 
See video:

![abc!](https://user-images.githubusercontent.com/29114032/150980715-fc21e85d-b5ab-488d-8f51-39689cd5bf47.gif)

**Comment by tasseKATT** [comment]
Will fix.
