### ISSUE TITLE
Best Fit Line: The tooltip formula does not apply to RTL

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#216]
1: Turn on best fit line
2: Turn on RTL
Check tooltip

If it should be handling RTL that is? Don't really know with math formulas

**Comment by T-Wizard** [comment]
@pernyl what do you expect to be different for RTL

**Comment by pernyl** [comment]
We discussed it a bit and it will not look good if we try to change the formula in an RTL way. Better to leave it as it is
