### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#217]
1: In consumer sales app create a scatter with Product, Actual Amount and Sales $
2: Always select the bin with most data
3: Finally around 1000 data points should be selected by I can't see them?
Even if I zoom in and out I can't find those 1000 values

See movie:

![abc!](https://user-images.githubusercontent.com/29114032/151546593-3a4d299c-081e-4021-8db9-98e19087e567.gif)

**Comment by quanho** [comment]
It is 1004 points so it is still in the compression mode.

**Comment by quanho** [comment]
It happens to old scatter plot too. The problem is all data points have zero for both axes.

**Comment by pernyl** [comment]
Yes but in the old you still see the data

**Comment by quanho** [comment]
I don't see the data in the old scatter plot.

**Comment by quanho** [comment]
Actually it is too small to see.

**Comment by pernyl** [comment]
as I remember I could at least zoom in to see the data and find the data in the old. In the new I could'nt even do that
