### ISSUE TITLE
Granularity on the axis is not the same in new

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#248]
In new the tics can be the same 0.88 0.88 but in old this is changed to 0.88 0.885 and so on

See image:
![Capture](https://user-images.githubusercontent.com/29114032/153197686-5f5d869b-1fd5-4af3-a5f5-0f4fc60739a4.PNG)

**Comment by bao-ho** [comment]
Never mind. I know how to fix this.
