### ISSUE TITLE
navigation panel: misplaced after turn on flag for old scatterplot

### ISSUE THREAD

**Issue by jjxie** [qlik-oss/sn-scatter-plot#253]
1. Create an old scatterplot with navigation on
2. Turn on feature flag SCATTER_PLOT
3. Can see the navigation panel is on the left even it is not rtl. Click on move left, left button is off screen.

![Screenshot 2022-02-11 at 12 59 06](https://user-images.githubusercontent.com/25456307/153588108-4c735451-3bbf-4c2a-a95a-78faba95a092.png)

![Screenshot 2022-02-11 at 13 02 44](https://user-images.githubusercontent.com/25456307/153588256-d86cb5aa-324d-4298-868f-356c1a62ba65.png)

**Comment by bao-ho** [comment]
I can't reproduce this bug.

**Comment by jjxie** [comment]
Can't reproduce it. Close it
