### ISSUE TITLE
After a selection the compressed data looks a bit bad

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-scatter-plot#263]
1: Choose city compton
2: Notice how the binned data looks a bit bad. The Y-axis seem to have too many decimals as well
Open APP and go to sheet Scatterplot

![abc!](https://user-images.githubusercontent.com/29114032/154636940-8bb451d3-1bd7-44d8-997d-d13660ee5c1f.gif)

APP: [Consumer Sales with mastercolor - bullet chart.zip](https://github.com/qlik-oss/sn-scatter-plot/files/8094952/Consumer.Sales.with.mastercolor.-.bullet.chart.zip)

**Comment by pernyl** [comment]
Might be correct however it is handled differently in the old:
![Capture](https://user-images.githubusercontent.com/29114032/154637820-87d9d5d8-a797-46f4-aab5-73fd87128390.PNG)

The reason is that "Actual Amount is 136859.48 for almost all of the values

**Comment by jjxie** [comment]
It's related to Quan's fix of https://github.com/qlik-oss/sn-scatter-plot/issues/217 I think

**Comment by quanho** [comment]
I can improve this a bit!
