### ISSUE TITLE
Reference to scatterplot lib incorrect?

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/sn-scatter-plot#34]
![image](https://user-images.githubusercontent.com/8709292/124278864-cec86300-db14-11eb-8961-581d0dc2dd2f.png)

I expect the lib to be @nebula.js/sn-scatterplot, not @scatterplot. Please help me understand if the intent is for it to be different.

**Comment by veinfors** [comment]
Absolutely! That was a typo from our side. Should be fixed by now.
