### ISSUE TITLE
stardust@1.1.1:45 TypeError: e.usePlugins is not a function

### ISSUE THREAD

**Issue by dipankarqlik** [qlik-oss/sn-scatter-plot#39]
Hi, I was trying to test the scatter plot chart in Nebula and loaded them like below:

**HTML:**
<script src="https://unpkg.com/@nebula.js/sn-scatter-plot"></script>

**JS:**
{
        name: 'scatterplot',
        load: () => Promise.resolve(window["sn-scatter-plot"])
      },

 nuked.render({
     element: document.querySelector(".object"),
      id: "mPFcgw",
  });

I am basically pulling an object from my QS App.

I end up with this error every time - 

TypeError: e.usePlugins is not a function
    at hj (sn-scatter-plot:11)
    at component (sn-scatter-plot:11)
    at stardust@1.1.1:45
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at r (stardust@1.1.1:7)
    at l (stardust@1.1.1:7)
    at stardust@1.1.1:7
    at new Promise (<anonymous>)

Looks like something is wrong with the package.

**Comment by veinfors** [comment]
Hi @dipankarqlik! The sn-scatter-plot requires version 1.2.0 or later of `@nebula.js/stardust`. We should probably communicate that better… Thanks for submitting the issue. Let me know if you still have problems with a later nebula version.
