### ISSUE TITLE
Increase binning limit

### ISSUE THREAD

**Issue by zangerls** [qlik-oss/sn-scatter-plot#429]
Hi!

Can we expect the limit at which data gets binned to increase in the (near) future? The native scatter plot has supported [up to 100.000 individual data points](https://community.qlik.com/t5/Suggest-an-Idea/Scatter-plot-compression-change-number-of-data-points-above/idi-p/1739746) for almost a year now in SaaS and roughly seven months in client managed.

This change would be very much appreciated as it is a (major) road block in our company's next product release.

Thanks a bunch and keep up the amazing work!

EDIT:

I just found `MAX_NR_SCATTER` in `src/constants/numbers.js`. Is there a particular reason for the limit to still be capped at 1000? Otherwise I could open a pull request to increase that number to match newer QlikSense versions.

Thanks!

**Comment by quanho** [comment]
MAX_NR_SCATTER is kept there to make it compatible with scatter plots in old versions. Changing that value does not increase the number of visible bubbles. MAX_VISIBLE_BUBBLES is the thing decide the max number of visible bubbles.
